<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PurchaseOrderInProgressSgt1Seeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        // Get SGT 1 department ID
        $sgt1DepartmentId = DB::table('departments')->where('name', 'SGT 1')->value('id');
        if (!$sgt1DepartmentId) {
            $this->command->error('SGT 1 department not found. Please run DepartmentSeeder first.');
            return;
        }

        // Get perihal IDs
        $perihalIds = DB::table('perihals')->pluck('id')->toArray();
        if (empty($perihalIds)) {
            $this->command->error('No perihals found. Please run PerihalSeeder first.');
            return;
        }

        // Get user ID for created_by
        $userId = DB::table('users')->value('id') ?? 1;

        // Get supplier IDs if available
        $supplierIds = DB::table('suppliers')->pluck('id')->toArray();
        $supplierId = !empty($supplierIds) ? $supplierIds[array_rand($supplierIds)] : null;

        // Get bank IDs if available
        $bankIds = DB::table('banks')->pluck('id')->toArray();
        $bankId = !empty($bankIds) ? $bankIds[array_rand($bankIds)] : null;

        // Get PPh IDs if available
        $pphIds = DB::table('pphs')->pluck('id')->toArray();
        $pphId = !empty($pphIds) ? $pphIds[array_rand($pphIds)] : null;

        // Get termin IDs if available
        $terminIds = DB::table('termins')->pluck('id')->toArray();
        $terminId = !empty($terminIds) ? $terminIds[array_rand($terminIds)] : null;

        $purchaseOrders = [
            [
                'no_po' => 'PO-SGT1-2024-001',
                'tipe_po' => 'Reguler',
                'department_id' => $sgt1DepartmentId,
                'perihal_id' => $perihalIds[array_rand($perihalIds)],
                'no_invoice' => 'INV-SGT1-001',
                'harga' => 2500000.00,
                'total' => 2500000.00,
                'detail_keperluan' => 'Pembelian mesin produksi untuk departemen SGT 1',
                'tanggal' => $now->copy()->subDays(5),
                'status' => 'In Progress',
                'metode_pembayaran' => 'Transfer',
                'bank_id' => $bankId,
                'nama_rekening' => 'PT SGT Manufacturing',
                'no_rekening' => '1234567890',
                'no_kartu_kredit' => null,
                'no_giro' => null,
                'tanggal_giro' => null,
                'tanggal_cair' => null,
                'created_by' => $userId,
                'updated_by' => null,
                'canceled_by' => null,
                'canceled_at' => null,
                'approved_by' => null,
                'approved_at' => null,
                'approval_notes' => null,
                'rejected_by' => null,
                'rejected_at' => null,
                'rejection_reason' => null,
                'dokumen' => 'dokumen_po_001.pdf',
                'cicilan' => null,
                'termin' => null,
                'nominal' => null,
                'keterangan' => 'Pembelian untuk kebutuhan produksi',
                'diskon' => 0.00,
                'ppn' => true,
                'ppn_nominal' => 250000.00,
                'pph_id' => $pphId,
                'termin_id' => $terminId,
                'pph_nominal' => 125000.00,
                'grand_total' => 2875000.00,
                'supplier_id' => $supplierId,
                'created_at' => $now->copy()->subDays(5),
                'updated_at' => $now->copy()->subDays(3),
            ],
            [
                'no_po' => 'PO-SGT1-2024-002',
                'tipe_po' => 'Lainnya',
                'department_id' => $sgt1DepartmentId,
                'perihal_id' => $perihalIds[array_rand($perihalIds)],
                'no_invoice' => 'INV-SGT1-002',
                'harga' => 1500000.00,
                'total' => 1500000.00,
                'detail_keperluan' => 'Pembelian bahan baku tekstil untuk SGT 1',
                'tanggal' => $now->copy()->subDays(4),
                'status' => 'In Progress',
                'metode_pembayaran' => 'Cash',
                'bank_id' => null,
                'nama_rekening' => null,
                'no_rekening' => null,
                'no_kartu_kredit' => null,
                'no_giro' => null,
                'tanggal_giro' => null,
                'tanggal_cair' => null,
                'created_by' => $userId,
                'updated_by' => null,
                'canceled_by' => null,
                'canceled_at' => null,
                'approved_by' => null,
                'approved_at' => null,
                'approval_notes' => null,
                'rejected_by' => null,
                'rejected_at' => null,
                'rejection_reason' => null,
                'dokumen' => 'dokumen_po_002.pdf',
                'cicilan' => null,
                'termin' => null,
                'nominal' => null,
                'keterangan' => 'Pembelian bahan baku',
                'diskon' => 50000.00,
                'ppn' => false,
                'ppn_nominal' => 0.00,
                'pph_id' => null,
                'termin_id' => null,
                'pph_nominal' => 0.00,
                'grand_total' => 1450000.00,
                'supplier_id' => $supplierId,
                'created_at' => $now->copy()->subDays(4),
                'updated_at' => $now->copy()->subDays(2),
            ],
            [
                'no_po' => 'PO-SGT1-2024-003',
                'tipe_po' => 'Reguler',
                'department_id' => $sgt1DepartmentId,
                'perihal_id' => $perihalIds[array_rand($perihalIds)],
                'no_invoice' => 'INV-SGT1-003',
                'harga' => 3200000.00,
                'total' => 3200000.00,
                'detail_keperluan' => 'Pembelian spare parts mesin untuk maintenance SGT 1',
                'tanggal' => $now->copy()->subDays(3),
                'status' => 'In Progress',
                'metode_pembayaran' => 'Transfer',
                'bank_id' => $bankId,
                'nama_rekening' => 'PT SGT Manufacturing',
                'no_rekening' => '1234567890',
                'no_kartu_kredit' => null,
                'no_giro' => null,
                'tanggal_giro' => null,
                'tanggal_cair' => null,
                'created_by' => $userId,
                'updated_by' => null,
                'canceled_by' => null,
                'canceled_at' => null,
                'approved_by' => null,
                'approved_at' => null,
                'approval_notes' => null,
                'rejected_by' => null,
                'rejected_at' => null,
                'rejection_reason' => null,
                'dokumen' => 'dokumen_po_003.pdf',
                'cicilan' => null,
                'termin' => null,
                'nominal' => null,
                'keterangan' => 'Pembelian spare parts maintenance',
                'diskon' => 0.00,
                'ppn' => true,
                'ppn_nominal' => 320000.00,
                'pph_id' => $pphId,
                'termin_id' => $terminId,
                'pph_nominal' => 160000.00,
                'grand_total' => 3680000.00,
                'supplier_id' => $supplierId,
                'created_at' => $now->copy()->subDays(3),
                'updated_at' => $now->copy()->subDays(1),
            ],
            [
                'no_po' => 'PO-SGT1-2024-004',
                'tipe_po' => 'Lainnya',
                'department_id' => $sgt1DepartmentId,
                'perihal_id' => $perihalIds[array_rand($perihalIds)],
                'no_invoice' => 'INV-SGT1-004',
                'harga' => 800000.00,
                'total' => 800000.00,
                'detail_keperluan' => 'Pembayaran jasa konsultan untuk SGT 1',
                'tanggal' => $now->copy()->subDays(2),
                'status' => 'In Progress',
                'metode_pembayaran' => 'Giro',
                'bank_id' => $bankId,
                'nama_rekening' => 'PT SGT Manufacturing',
                'no_rekening' => '1234567890',
                'no_kartu_kredit' => null,
                'no_giro' => 'GIR-001-2024',
                'tanggal_giro' => $now->copy()->addDays(30),
                'tanggal_cair' => $now->copy()->addDays(30),
                'created_by' => $userId,
                'updated_by' => null,
                'canceled_by' => null,
                'canceled_at' => null,
                'approved_by' => null,
                'approved_at' => null,
                'approval_notes' => null,
                'rejected_by' => null,
                'rejected_at' => null,
                'rejection_reason' => null,
                'dokumen' => 'dokumen_po_004.pdf',
                'cicilan' => null,
                'termin' => null,
                'nominal' => null,
                'keterangan' => 'Pembayaran jasa konsultan',
                'diskon' => 0.00,
                'ppn' => false,
                'ppn_nominal' => 0.00,
                'pph_id' => $pphId,
                'termin_id' => null,
                'pph_nominal' => 40000.00,
                'grand_total' => 840000.00,
                'supplier_id' => $supplierId,
                'created_at' => $now->copy()->subDays(2),
                'updated_at' => $now->copy()->subDays(1),
            ],
            [
                'no_po' => 'PO-SGT1-2024-005',
                'tipe_po' => 'Reguler',
                'department_id' => $sgt1DepartmentId,
                'perihal_id' => $perihalIds[array_rand($perihalIds)],
                'no_invoice' => 'INV-SGT1-005',
                'harga' => 4500000.00,
                'total' => 4500000.00,
                'detail_keperluan' => 'Pembelian peralatan laboratorium untuk SGT 1',
                'tanggal' => $now->copy()->subDays(1),
                'status' => 'In Progress',
                'metode_pembayaran' => 'Kartu Kredit',
                'bank_id' => $bankId,
                'nama_rekening' => null,
                'no_rekening' => null,
                'no_kartu_kredit' => '4111-1111-1111-1111',
                'no_giro' => null,
                'tanggal_giro' => null,
                'tanggal_cair' => null,
                'created_by' => $userId,
                'updated_by' => null,
                'canceled_by' => null,
                'canceled_at' => null,
                'approved_by' => null,
                'approved_at' => null,
                'approval_notes' => null,
                'rejected_by' => null,
                'rejected_at' => null,
                'rejection_reason' => null,
                'dokumen' => 'dokumen_po_005.pdf',
                'cicilan' => 3,
                'termin' => 3,
                'nominal' => 1500000.00,
                'keterangan' => 'Pembelian peralatan lab dengan cicilan 3x',
                'diskon' => 0.00,
                'ppn' => true,
                'ppn_nominal' => 450000.00,
                'pph_id' => $pphId,
                'termin_id' => $terminId,
                'pph_nominal' => 225000.00,
                'grand_total' => 5175000.00,
                'supplier_id' => $supplierId,
                'created_at' => $now->copy()->subDays(1),
                'updated_at' => $now,
            ],
            [
                'no_po' => 'PO-SGT1-2024-006',
                'tipe_po' => 'Lainnya',
                'department_id' => $sgt1DepartmentId,
                'perihal_id' => $perihalIds[array_rand($perihalIds)],
                'no_invoice' => 'INV-SGT1-006',
                'harga' => 1200000.00,
                'total' => 1200000.00,
                'detail_keperluan' => 'Pembelian software lisensi untuk SGT 1',
                'tanggal' => $now,
                'status' => 'In Progress',
                'metode_pembayaran' => 'Transfer',
                'bank_id' => $bankId,
                'nama_rekening' => 'PT SGT Manufacturing',
                'no_rekening' => '1234567890',
                'no_kartu_kredit' => null,
                'no_giro' => null,
                'tanggal_giro' => null,
                'tanggal_cair' => null,
                'created_by' => $userId,
                'updated_by' => null,
                'canceled_by' => null,
                'canceled_at' => null,
                'approved_by' => null,
                'approved_at' => null,
                'approval_notes' => null,
                'rejected_by' => null,
                'rejected_at' => null,
                'rejection_reason' => null,
                'dokumen' => 'dokumen_po_006.pdf',
                'cicilan' => null,
                'termin' => null,
                'nominal' => null,
                'keterangan' => 'Pembelian software lisensi',
                'diskon' => 100000.00,
                'ppn' => false,
                'ppn_nominal' => 0.00,
                'pph_id' => null,
                'termin_id' => null,
                'pph_nominal' => 0.00,
                'grand_total' => 1100000.00,
                'supplier_id' => $supplierId,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'no_po' => 'PO-SGT1-2024-007',
                'tipe_po' => 'Reguler',
                'department_id' => $sgt1DepartmentId,
                'perihal_id' => $perihalIds[array_rand($perihalIds)],
                'no_invoice' => 'INV-SGT1-007',
                'harga' => 2800000.00,
                'total' => 2800000.00,
                'detail_keperluan' => 'Pembelian mesin pendingin untuk SGT 1',
                'tanggal' => $now->copy()->addDays(1),
                'status' => 'In Progress',
                'metode_pembayaran' => 'Transfer',
                'bank_id' => $bankId,
                'nama_rekening' => 'PT SGT Manufacturing',
                'no_rekening' => '1234567890',
                'no_kartu_kredit' => null,
                'no_giro' => null,
                'tanggal_giro' => null,
                'tanggal_cair' => null,
                'created_by' => $userId,
                'updated_by' => null,
                'canceled_by' => null,
                'canceled_at' => null,
                'approved_by' => null,
                'approved_at' => null,
                'approval_notes' => null,
                'rejected_by' => null,
                'rejected_at' => null,
                'rejection_reason' => null,
                'dokumen' => 'dokumen_po_007.pdf',
                'cicilan' => null,
                'termin' => null,
                'nominal' => null,
                'keterangan' => 'Pembelian mesin pendingin',
                'diskon' => 0.00,
                'ppn' => true,
                'ppn_nominal' => 280000.00,
                'pph_id' => $pphId,
                'termin_id' => $terminId,
                'pph_nominal' => 140000.00,
                'grand_total' => 3220000.00,
                'supplier_id' => $supplierId,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'no_po' => 'PO-SGT1-2024-008',
                'tipe_po' => 'Lainnya',
                'department_id' => $sgt1DepartmentId,
                'perihal_id' => $perihalIds[array_rand($perihalIds)],
                'no_invoice' => 'INV-SGT1-008',
                'harga' => 950000.00,
                'total' => 950000.00,
                'detail_keperluan' => 'Pembelian peralatan keselamatan kerja untuk SGT 1',
                'tanggal' => $now->copy()->addDays(2),
                'status' => 'In Progress',
                'metode_pembayaran' => 'Cash',
                'bank_id' => null,
                'nama_rekening' => null,
                'no_rekening' => null,
                'no_kartu_kredit' => null,
                'no_giro' => null,
                'tanggal_giro' => null,
                'tanggal_cair' => null,
                'created_by' => $userId,
                'updated_by' => null,
                'canceled_by' => null,
                'canceled_at' => null,
                'approved_by' => null,
                'approved_at' => null,
                'approval_notes' => null,
                'rejected_by' => null,
                'rejected_at' => null,
                'rejection_reason' => null,
                'dokumen' => 'dokumen_po_008.pdf',
                'cicilan' => null,
                'termin' => null,
                'nominal' => null,
                'keterangan' => 'Pembelian peralatan K3',
                'diskon' => 50000.00,
                'ppn' => false,
                'ppn_nominal' => 0.00,
                'pph_id' => null,
                'termin_id' => null,
                'pph_nominal' => 0.00,
                'grand_total' => 900000.00,
                'supplier_id' => $supplierId,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'no_po' => 'PO-SGT1-2024-009',
                'tipe_po' => 'Reguler',
                'department_id' => $sgt1DepartmentId,
                'perihal_id' => $perihalIds[array_rand($perihalIds)],
                'no_invoice' => 'INV-SGT1-009',
                'harga' => 3800000.00,
                'total' => 3800000.00,
                'detail_keperluan' => 'Pembelian conveyor belt untuk SGT 1',
                'tanggal' => $now->copy()->addDays(3),
                'status' => 'In Progress',
                'metode_pembayaran' => 'Transfer',
                'bank_id' => $bankId,
                'nama_rekening' => 'PT SGT Manufacturing',
                'no_rekening' => '1234567890',
                'no_kartu_kredit' => null,
                'no_giro' => null,
                'tanggal_giro' => null,
                'tanggal_cair' => null,
                'created_by' => $userId,
                'updated_by' => null,
                'canceled_by' => null,
                'canceled_at' => null,
                'approved_by' => null,
                'approved_at' => null,
                'approval_notes' => null,
                'rejected_by' => null,
                'rejected_at' => null,
                'rejection_reason' => null,
                'dokumen' => 'dokumen_po_009.pdf',
                'cicilan' => null,
                'termin' => null,
                'nominal' => null,
                'keterangan' => 'Pembelian conveyor belt',
                'diskon' => 0.00,
                'ppn' => true,
                'ppn_nominal' => 380000.00,
                'pph_id' => $pphId,
                'termin_id' => $terminId,
                'pph_nominal' => 190000.00,
                'grand_total' => 4370000.00,
                'supplier_id' => $supplierId,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'no_po' => 'PO-SGT1-2024-010',
                'tipe_po' => 'Lainnya',
                'department_id' => $sgt1DepartmentId,
                'perihal_id' => $perihalIds[array_rand($perihalIds)],
                'no_invoice' => 'INV-SGT1-010',
                'harga' => 1800000.00,
                'total' => 1800000.00,
                'detail_keperluan' => 'Pembelian peralatan kantor untuk SGT 1',
                'tanggal' => $now->copy()->addDays(4),
                'status' => 'In Progress',
                'metode_pembayaran' => 'Kartu Kredit',
                'bank_id' => $bankId,
                'nama_rekening' => null,
                'no_rekening' => null,
                'no_kartu_kredit' => '4111-2222-3333-4444',
                'no_giro' => null,
                'tanggal_giro' => null,
                'tanggal_cair' => null,
                'created_by' => $userId,
                'updated_by' => null,
                'canceled_by' => null,
                'canceled_at' => null,
                'approved_by' => null,
                'approved_at' => null,
                'approval_notes' => null,
                'rejected_by' => null,
                'rejected_at' => null,
                'rejection_reason' => null,
                'dokumen' => 'dokumen_po_010.pdf',
                'cicilan' => 2,
                'termin' => 2,
                'nominal' => 900000.00,
                'keterangan' => 'Pembelian peralatan kantor dengan cicilan 2x',
                'diskon' => 0.00,
                'ppn' => false,
                'ppn_nominal' => 0.00,
                'pph_id' => null,
                'termin_id' => null,
                'pph_nominal' => 0.00,
                'grand_total' => 1800000.00,
                'supplier_id' => $supplierId,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        // Insert purchase orders
        foreach ($purchaseOrders as $po) {
            DB::table('purchase_orders')->insert($po);
        }

        // Get the inserted PO IDs
        $poIds = DB::table('purchase_orders')
            ->where('department_id', $sgt1DepartmentId)
            ->where('status', 'In Progress')
            ->pluck('id');

        // Insert sample purchase order items for each PO
        foreach ($poIds as $poId) {
            DB::table('purchase_order_items')->insert([
                [
                    'purchase_order_id' => $poId,
                    'nama_barang' => 'Barang SGT1-' . $poId . '-A',
                    'qty' => rand(5, 20),
                    'satuan' => 'pcs',
                    'harga' => rand(50000, 500000),
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'purchase_order_id' => $poId,
                    'nama_barang' => 'Barang SGT1-' . $poId . '-B',
                    'qty' => rand(2, 10),
                    'satuan' => 'unit',
                    'harga' => rand(100000, 1000000),
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'purchase_order_id' => $poId,
                    'nama_barang' => 'Barang SGT1-' . $poId . '-C',
                    'qty' => rand(1, 5),
                    'satuan' => 'set',
                    'harga' => rand(200000, 2000000),
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
            ]);
        }

        $this->command->info('Purchase Order In Progress SGT 1 seeder completed successfully!');
        $this->command->info('Created ' . count($purchaseOrders) . ' purchase orders with status "In Progress" for department "SGT 1"');
    }
}
